### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by Legobas** [niveksan/rclone-crond#19]
Thank you for this nice and simple solution!

I wanted the rclone actions to be logged and did it like this in backup.sh:

    rclone sync -v --stats-one-line Local:/data/bitwarden_rs-local-backup/backups Nextcloud:/Bitwarden >> /proc/1/fd/1 2>&1

It will show stdout as well as stderr logs in de docker log.
Maybe you can add this to de benefit of other users.

**Comment by niveksan** [comment]
Works great. Nice addition, thank you.
